const cardPersonActionTypes = {
  SET_CARD_PERSON_OPEN: "SET_CARD_PERSON_OPEN",
  SET_CARD_PERSON_CLOSE: "SET_CARD_PERSON_CLOSE",
  SET_CARD_PERSON_TOGGLE: "SET_CARD_PERSON_TOGGLE",
};

export default cardPersonActionTypes;
