const directoryActionTypes = {
  FETCH_DIRECTORY_START: "FETCH_DIRECTORY_START",
  FETCH_DIRECTORY_SUCCESS: "FETCH_DIRECTORY_SUCCESS",
  FETCH_DIRECTORY_FAIL: "FETCH_DIRECTORY_FAIL",
};

export default directoryActionTypes;
